#name: my-ci-flow test
#on: [push]
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#  steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v2



name: Python application test workflow

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        # Install any other dependencies you might have

    - name: Run Tests
      run: |
        python -m unittest discover -s ./test -p '*_teams.py'

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Report
        path: https://github.com/NajeebJaba/BallDontLieBack-EndProject.git





    
