name: Python application test workflow

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run tests
      run: |
        python -m unittest discover -s ./test -p '*mean_teams.py'
    
              








    
